# Generated by Django 2.2.6 on 2019-11-03 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20191102_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
