# Generated by Django 2.2.6 on 2019-11-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='FuelTrack',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
